media_folder: "public/assets/content" # Emplacement où les fichiers seront stockés dans le dépôt
public_folder: "assets/content" # L'attribut src pour les médias téléchargés
backend:
  name: git-gateway
  branch: main # Branch to update
  #  branch: feature/source-from-netlifycms # Branch to update
  # local_backend: true

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "biomes"
    extension: "json"
    label: "Biomes"
    label_singular: "Biome"
    folder: "src/content/biomes"
    create: true
    delete: true
    identifier_field: "name"
    fields:
      - { name: "name", label: "Nom", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      - {
          name: "biomesImage",
          widget: "image",
          label: "Image du biome",
        }
      - { name: "heroDescription", label: "Description du hero", widget: "string" }
      - { name: "description", label: "Description complète", widget: "string" }
      - { name: "climat", label: "Climat", widget: "string" }
      - { name: "temperatureMin", label: "Température minimale", widget: "string" }
      - { name: "temperatureMax", label: "Température maximale", widget: "string" }
      - { name: "speciesNumber", label: "Présence animale", widget: "string" }
      - { name: "color", label: "Color", widget: "color" }

  - name: "species"
    extension: "json"
    label: "Espèces"
    label_singular: "Espèce"
    folder: "src/content/species"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    identifier_field: "name"
    fields:
      - { name: "id", widget: "string", label: "Id" }
      - { name: "name", widget: "string", label: "Nom" }
      - {
          name: "speciesImage",
          widget: "image",
          label: "Image de la nouvelle espèce",
        }
      - {
          name: "discoveryDate",
          widget: "datetime",
          format: "DD MMM YYYY",
          date_format: "DD MMM YYYY",
          time_format: true,
          label: "Date de la découverte",
        }
      - {
          name: "type",
          label: "Type",
          widget: "select",
          default: "plant",
          options:
            [
              { label: "Plante", value: "plant" },
              { label: "Animal", value: "animal" },
            ],
        }
      - {
          name: "biome",
          label: "Biome",
          widget: "relation",
          collection: "biomes",
          search_fields: ["name"],
          value_field: "name",
          display_fields: ["name"],
        }
      - {
          name: "height",
          widget: "string",
          value_type: "string",
          label: "Taille",
          required: true,
        }
      - {
          name: "weight",
          widget: "string",
          value_type: "string",
          label: "poids",
          required: false,
        }
      - {
          name: "life",
          widget: "string",
          label: "Durée de vie",
          required: false,
        }
      - {
          name: "diet",
          label: "Régime alimentaire",
          widget: "select",
          default: "Carnivore",
          options:
            [
              { label: "Carnivore", value: "carnivore" },
              { label: "Herbivore", value: "herbivore" },
            ],
        }
      - {
          name: "EvolutionDescription",
          widget: "markdown",
          label: "Description détaillée de son évolution",
          required: false,
        }
      - {
          name: "expedition",
          widget: "string",
          label: "Numéro d'exploration",
          required: false,
        }
      - {
          name: "explorator",
          widget: "string",
          label: "Explorateur",
          required: false,
        }
  - name: "modules"
    extension: "json"
    label: "Modules"
    label_singular: "Module"
    folder: "src/content/modules"
    create: true
    delete: true
    identifier_field: "name"
    fields:
      - {
          name: "discoveryDate",
          widget: "datetime",
          format: "DD MMM YYYY",
          date_format: "DD MMM YYYY",
          time_format: "HH:mm",
          label: "Date de la découverte",
        }
      - label: "url"
        name: "slug"
        widget: "string"
        default: "{{slug}}"
        required: true
      - label: "PDF"
        name: "pdf"
        widget: "file"

      - label: "Titre de la preview"
        name: "previewTitle"
        widget: "string"
        required: true

      - label: "Sous titre de la preview"
        name: "previewSubTitle"
        widget: "string"
        required: false

      - label: "Image de la preview"
        name: "previewImage"
        widget: "image"
        required: true

      - label: "Titre de la page"
        name: "title"
        widget: "string"
        default: "Les Animaux du futur"
        required: true

      - label: "Contenu du hero"
        name: "HeroContent"
        widget: "markdown"
        required: false

      -
        label: "hero Background"
        name: "background"
        widget: "image"
        required: true
      -
        label: "Index"
        name: "index"
        widget: "number"
        required: true

      - label: "Sections"
        name: "sections"
        widget: "list"
        summary: '{{fields.Section.title}}'
        required: false
        fields: [{ label: Section,
                  name: section,
                  widget: object,
                  fields:  [{label: Titre, name: title, widget: string},{label: Content, name: content, widget: markdown}, {label: "Image", name: "image", widget: "image", required: false,}]}]


  - name: "Pages" # Utilisé dans les routes, par exemple, /admin/collections/blog
    label: "Pages" # Utilisé dans l'UI
    create: true # Permettre aux utilisateurs de créer de nouveaux documents dans cette collection
    extension: "json"
    files:
      - file: "src/content/pages/home.json"
        name: "homePage"
        label: "Page d'accueil"
        fields:
          - {
              label: "Titre de la page",
              name: "title",
              widget: "string",
              default: "Les Animaux du futur",
              required: true,
            }
          - {
              label: "Contenu du hero",
              name: "HeroContent",
              widget: "markdown",
              required: false,
            }
          - {
              label: "Bouttons",
              name: "heroBtns",
              widget: "list",
              summary: '{{fields.Btn.text}}',
              required: false,
              fields: [{ label: Boutton,
                        name: Btn,
                        widget: object,
                        fields:  [{label: Text, name: text, widget: string},{label: Lien, name: link, widget: string}]}]
            }
          - {
              label: "hero Background",
              name: "background",
              widget: "image",
              required: true,
            }
          - {
              label: "Titre de la première section",
              name: "firstSectionTitle",
              widget: "string",
            }
          - {
              label: "Contenu de la première section",
              name: "firstSectionContent",
              widget: "markdown",
            }
          - {
              label: "Image de la première section",
              name: "firstSectionImg",
              widget: "image",
              required: true,
            }
          - {
              label: "Titre de la deuxième section",
              name: "SecondSectionTitle",
              widget: "string",
            }
          - {
              label: "Contenu de la deuxième section",
              name: "SecondSectionContent",
              widget: "markdown",
            }
      - file: "src/content/pages/coulisses.json"
        name: "Coulisses"
        label: "Page des coulisses"
        fields:
          - label: "Url de la page"
            name: "url"
            widget: "string"
            default: "coulisses"
            required: false

          - label: "Titre de la page"
            name: "title"
            widget: "string"
            default: "Les coulisses"
            required: true

          - label: "Contenu du hero"
            name: "HeroContent"
            widget: "markdown"
            required: false

          - label: "Bouttons"
            name: "heroBtns"
            widget: "list"
            summary: '{{fields.Btn.text}}'
            required: false
            fields: [{ label: Boutton,
                      name: Btn,
                      widget: object,
                      fields:  [{label: Text, name: text, widget: string},{label: Lien, name: link, widget: string}]}]

          - label: "hero Background"
            name: "background"
            widget: "image"
            required: true

          - label: "Titre de la première section"
            name: "firstSectionTitle"
            widget: "string"

          - label: "Contenu de la première section"
            name: "firstSectionContent"
            widget: "markdown"

          - label: "Sections"
            name: "sections"
            widget: "list"
            summary: '{{fields.Section.title}}'
            required: false
            fields: [{ label: Section,
                      name: section,
                      widget: object,
                      fields:  [{label: Titre, name: title, widget: string},{label: Content, name: content, widget: markdown}, {label: "Image", name: "image", widget: "image", required: false}, {label: "BoutonText", name: "btnText", widget: "string", required: false,}, {label: "Lien du bouton", name: "btnLink", widget: "string", required: false,}]}]
